eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9022
spring:
  application:
    name: KYC Approval Web

#开放所有页面节点  默认只开启了health、info两个节点

management:
  endpoints:
    web:
      exposure:
        include: '*'